# Generated by Django 4.2.16 on 2025-08-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='aula',
            field=models.CharField(default='Trabalho de Conclusão de Curso', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='curso',
            field=models.CharField(default='Engenharia da Computação', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(default='11111111111111', max_length=50),
            preserve_default=False,
        ),
    ]
