# Generated by Django 4.2.16 on 2025-12-04 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_funcionario_aula_funcionario_curso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Alunos', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='aula',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='curso',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='RegistroFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.funcionario')),
            ],
        ),
    ]
